<?php 

add_role('order_manager', __(
   'Order Manager'),
   array(
    "level_9" => 1,
    "level_8" => 1,
    "level_7" => 1,
    "level_6" => 1,
    "level_5" => 1,
    "level_4" => 1,
    "level_3" => 1,
    "level_2" => 1,
    "level_1," => 1,
    "level_0" => 1,
    "read" => 1,
    "read_private_pages" => 1,
    "read_private_posts" => 1,
    "edit_posts" => 1,
    "edit_pages" => 1,
    "edit_published_posts" => 1,
    "edit_published_pages" => 1,
    "edit_private_pages" => 1,
    "edit_private_posts" => 1,
    "edit_others_posts" => 1,
    "edit_others_pages" => 1,
    "publish_posts" => 1,
    "publish_pages" => 1,
    "delete_posts" => 1,
    "delete_pages" => 1,
    "delete_private_pages" => 1,
    "delete_private_posts" => 1,
    "delete_published_pages" => 1,
    "delete_published_posts" => 1,
    "delete_others_posts" => 1,
    "delete_others_pages" => 1,
    "manage_categories" => 1,
    "manage_links" => 1,
    "moderate_comments" => 1,
    "upload_files" => 1,
    "export" => 1,
    "import" => 1,
    "list_users" => 1,
    "manage_woocommerce" => 1,
    "view_woocommerce_reports" => 1,
    "edit_product" => 1,
    "read_product" => 1,
    "delete_product" => 1,
    "edit_products" => 1,
    "edit_others_products" => 1,
    "publish_products" => 1,
    "edit_shop_order" => 1,
    "read_shop_order" => 1,
    "delete_shop_order" => 1,
    "edit_shop_orders" => 1,
    "edit_others_shop_orders" => 1,
    "publish_shop_orders" => 1,
    "read_private_shop_orders" => 1,
    "delete_shop_orders" => 1,
    "delete_private_shop_orders" => 1,
    "delete_published_shop_orders" => 1,
    "delete_others_shop_orders" => 1,
    "edit_private_shop_orders" => 1,
    "edit_published_shop_orders" => 1,
    "manage_shop_order_terms" => 1,
    "edit_shop_order_terms" => 1,
    "delete_shop_order_terms" => 1,
    "assign_shop_order_terms" => 1,
 )

);



add_role('regional_manager', __(
   'Regional Manager'),
   array(
    "level_9" => 1,
    "level_8" => 1,
    "level_7" => 1,
    "level_6" => 1,
    "level_5" => 1,
    "level_4" => 1,
    "level_3" => 1,
    "level_2" => 1,
    "level_1," => 1,
    "level_0" => 1,
    "read" => 1,
    "read_private_pages" => 1,
    "read_private_posts" => 1,
    "edit_posts" => 1,
    "edit_pages" => 1,
    "edit_published_posts" => 1,
    "edit_published_pages" => 1,
    "edit_private_pages" => 1,
    "edit_private_posts" => 1,
    "edit_others_posts" => 1,
    "edit_others_pages" => 1,
    "publish_posts" => 1,
    "publish_pages" => 1,
    "delete_posts" => 1,
    "delete_pages" => 1,
    "delete_private_pages" => 1,
    "delete_private_posts" => 1,
    "delete_published_pages" => 1,
    "delete_published_posts" => 1,
    "delete_others_posts" => 1,
    "delete_others_pages" => 1,
    "manage_categories" => 1,
    "manage_links" => 1,
    "moderate_comments" => 1,
    "upload_files" => 1,
    "export" => 1,
    "import" => 1,
    "list_users" => 1,
    "manage_woocommerce" => 1,
    "view_woocommerce_reports" => 1,
    "edit_product" => 1,
    "read_product" => 1,
    "delete_product" => 1,
    "edit_products" => 1,
    "edit_others_products" => 1,
    "publish_products" => 1,
    "edit_shop_order" => 1,
    "read_shop_order" => 1,
    "delete_shop_order" => 1,
    "edit_shop_orders" => 1,
    "edit_others_shop_orders" => 1,
    "publish_shop_orders" => 1,
    "read_private_shop_orders" => 1,
    "delete_shop_orders" => 1,
    "delete_private_shop_orders" => 1,
    "delete_published_shop_orders" => 1,
    "delete_others_shop_orders" => 1,
    "edit_private_shop_orders" => 1,
    "edit_published_shop_orders" => 1,
    "manage_shop_order_terms" => 1,
    "edit_shop_order_terms" => 1,
    "delete_shop_order_terms" => 1,
    "assign_shop_order_terms" => 1,
 )

);



/*$role = get_role("shop_manager");
print_r($role->capabilities);*/

